---
- name: Httpd Installation
  hosts: "client1"
  tasks:
    - name: Package info
      yum:
        package: httpd
        state: Present
    - name: File Copy
      copy:
        dest: /var/www/html/index.html
        content: "<h1> Hello I am Abhimanyu</h1>"
    - name: Service start
      service:
        state: started
        name: httpd
    
